name: CI PIPe
on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
      run: npm ci
    - name: Code formating check
      run: npm run code:check
    - name: Aws authentication
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        aws-region: eu-north-1
    - name: Build Project
      if: git.event_name == 'push' && github.ref == 'refs/heads/develop'
      run: npm run build
    - name: Create Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: npx semantic-release
      env:
         GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}