name: Node.js CI

on:
  push:
    branches: [ "develop" ,"main"]
  pull_request:
    branches: [ "develop" ,"main"]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run code:check
    - name: Build Project
      run: npm run build
    - run: sudo pm2 restart backend
    - name: Create a new Release
      if: github.event_name == 'push' && github.ref == 'refs/head/main'
      run: npx semantic-release